name: edging_env
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.6.0=h6a678d5_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cffi=2.0.0=py310h4eded50_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcap=2.77=h3ff7636_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libfabric=2.3.1=ha770c72_1
  - libfabric1=2.3.1=h6c8fc0a_1
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_5
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h5eee18b_1
  - libpmix=5.0.8=h4bd6b51_2
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libsystemd0=258.2=h6569c3e_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.0=hde9077f_0
  - libudev1=258.2=h6569c3e_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0.1=openmpi
  - mpi4py=4.1.1=py310h42af892_101
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.7.3=hbbd107a_1
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openmpi=5.0.8=h2fe1745_108
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_0
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - rdma-core=60.0=hecca717_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.5.1=py310_cu121
  - torchtriton=3.1.0=py310
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h78e105d_0
  - ucc=1.6.0=hb729f83_0
  - ucx=1.19.0=h63b5c0b_5
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.2.2
      - accelerate==1.11.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - augmentor==0.2.12
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - deepspeed==0.18.2
      - dm-tree==0.1.9
      - easydict==1.13
      - einops==0.8.1
      - fonttools==4.58.0
      - fsspec==2025.3.2
      - gast==0.6.0
      - grpcio==1.71.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - huggingface-hub==0.36.0
      - idna==3.10
      - joblib==1.5.0
      - kiwisolver==1.4.0
      - llvmlite==0.45.1
      - markdown==3.8
      - matplotlib==3.9.0
      - msgpack==1.1.2
      - narwhals==2.9.0
      - networkx==3.2
      - ninja==1.13.0
      - numba==0.62.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-dali-cuda110==1.49.0
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvcomp-cu11==4.2.0.14
      - nvidia-nvimgcodec-cu11==0.5.0.13
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvjpeg-cu11==11.9.0.86
      - nvidia-nvjpeg2k-cu11==0.8.1.40
      - nvidia-nvtiff-cu11==0.5.0.67
      - nvidia-nvtx-cu12==12.6.77
      - onnx==1.17.0
      - opencv-python==4.11.0.86
      - pillow==11.2.1
      - plotly==6.3.1
      - protobuf==6.30.2
      - py-cpuinfo==9.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytorch-metric-learning==2.9.0
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.0
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - timm==1.0.15
      - tokenizers==0.22.1
      - torch==2.3.1+cu121
      - torchinfo==1.8.0
      - torchvision==0.18.1+cu121
      - torchviz==0.0.3
      - transformers==4.57.1
      - triton==2.3.1
      - typing-extensions==4.13.2
      - umap-learn==0.5.9.post2
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
prefix: /home/aryan/miniconda3/envs/edging_env
